### ISSUE TITLE
Cannot update to 3.8.1 in aws eu-north-1

### ISSUE THREAD

**Issue by slaskis** [convox/convox#536]
It's probably https://github.com/convox/convox/pull/529 which breaks `convox rack update` in the eu-north-1 region with this message:

```
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "0a1bca35-3fe4-4093-a6dc-70f1ae459f5d"
  },
  Message_: "Tagging an elastic gpu on create is not yet supported in this region."
}

  on .terraform/modules/system/terraform/cluster/aws/main.tf line 90, in resource "aws_eks_node_group" "cluster":
  90: resource "aws_eks_node_group" "cluster" {
```

**Comment by nightfury1204** [comment]
Hey @slaskis thanks for reporting, can you specify the node(the types of instances) you are using in your rack?

**Comment by slaskis** [comment]
the rack params are:

```
node_disk  100
node_type  m6g.large
region     eu-north-1
release    3.8.0
```

Could it be caused by [`elastic-gpu` here](https://github.com/convox/convox/pull/529/files#diff-1377015aed58dc52eea28e2b6635f2c8c4b9decc5b8fb2c54188dde608e92d77R158)?

**Comment by nightfury1204** [comment]
> the rack params are:
> 
> ```
> node_disk  100
> node_type  m6g.large
> region     eu-north-1
> release    3.8.0
> ```
> 
> Could it be caused by [`elastic-gpu` here](https://github.com/convox/convox/pull/529/files#diff-1377015aed58dc52eea28e2b6635f2c8c4b9decc5b8fb2c54188dde608e92d77R158)?

yes
