### ISSUE TITLE
SSL Certificates aren't working with v3

### ISSUE THREAD

**Issue by Jinkxed** [convox/convox#595]
I've tried creating a few ssl certificates and CNAME them to my rack.  

Every single one of them gives me the default `Kubernetes Ingress Controller Fake Certificate`

Expanding on how to troubleshoot this or even what we should be looking at would go a looong ways.

I've tried:
example.org
app.example.org
app.dev.example.org

CNAME created and pointed to `convox rack` -> Router

Tried reaching out to support@convox.com and sales@convox.com.  The login page on the community forum is broke.

**ANY** help would be appreciated here.

**Comment by Twsouza** [comment]
hi @Jinkxed!
you have to configure your custom domain inside of the convox.yml so the certificate can be issued, see https://docs.convox.com/deployment/custom-domains/

> The login page on the community forum is broke.

Thanks for letting us know, we'll have a look.

**Comment by Jinkxed** [comment]
I did that and tried every other way that has been documented or asked.  It just doesn't want to work.

Unfortunately I just had to rip it all out and do it from terraform.

It's to bad was hoping to become a customer this time around.

**Comment by nightfury1204** [comment]
> I did that and tried every other way that has been documented or asked. It just doesn't want to work.
> 
> Unfortunately I just had to rip it all out and do it from terraform.
> 
> It's to bad was hoping to become a customer this time around.

sorry to hear that. we use letsencrypt http-01 challenge. so the rack needs to be reachable using the domain.

**Comment by nightfury1204** [comment]
since there is no response assuming, you are able to fix it

**Comment by Jinkxed** [comment]
Actually I wasn't.  I ended up having to delete it all and move to another product.
