### ISSUE TITLE
cannot unmarshal !!str `....` into manifest.Certificate with convox v3.10.7

### ISSUE THREAD

**Issue by nathany-copia** [convox/convox#597]
```
❯ convox version
client: 3.10.7
server: 3.10.7
```

After upgrading our racks from 3.6.3 all the way to 3.10.7, our deploys are no longer working due to a YAML parse error.

```
Promoting RXECYSMJXUT... ERROR: yaml: unmarshal errors:
  line 4: cannot unmarshal !!str `portal....` into manifest.Certificate
```

Our `convox.yml` had a `certificate: ...` line that matched the comma-separated list of the `domains: ` line. Based on the [documentation](https://docs.convox.com/deployment/custom-domains/), it seems like this line may not be required? However, after removing the certificate lines from all the convox.yaml files, the error above persists when doing a new build and attempting to promote it.

Based on #557, it sounds like certificate still exists? But it doesn't appear to be documented.

Even a commands like `convox services` is giving the unmarshal error for some unknown reason. Is it stuck on the YAML for the currently released apps, and not allowing us to promote the new builds?

**Comment by nathany-copia** [comment]
Possibly related -- The Convox Dashboard says "An error has occurred while loading this content" when clicking on one of the apps in the Racks section.

**Comment by idyll** [comment]
The current workaround is to downgrade the rack to `3.10.1` which is before the change was introduced that needs the `certificate` key in the convox.yml

This allows a successful deploy without the key set.

Once that has happened you should be able to deploy again on `3.10.7`

NOTE: it's not good enough to just remote `certificate` from your YAML file. It needs to be removed on the *RUNNING* release or the promote step fails.

So this is a doozy....

**Comment by nathany-copia** [comment]
A series of changes that weren't breaking individually, but together became one. 

#557 actually was a breaking change for anyone who was behind by a few versions. @Twsouza

**Comment by idyll** [comment]
Also someone should update the docs and confirm that this is the new format for that key:

```
services:
  web:
    domain: test.example.com
    certificate:
      duration: 2160h
```

I am pretty sure this is the expected format, but it should be documented.

**Comment by nathany-copia** [comment]
The process @idyll outlined also resolved the issue in the Convox Dashboard:

> The Convox Dashboard says "An error has occurred while loading this content" when clicking on one of the apps in the Racks section.

**Comment by nathany-copia** [comment]
Thanks @yuriadams
