### ISSUE TITLE
BuildKit socket timeout on 3.12.0

### ISSUE THREAD

**Issue by beastawakens** [convox/convox#641]
Since upgrading a Rack to 3.12.0 , we're experiencing a lot of timeouts on build jobs/workflows with `could not connect to unix:///run/buildkit/buildkitd.sock after 10 trials` showing in the logs in Console.  The job never completes so it sits there spinning but is not actually doing anything, thereby holding up and delaying the subsequent jobs.

Looks a lot like this: https://github.com/moby/buildkit/issues/1423 which appears to have been fixed a few years ago with a configurable retry count env var.  Can we set that higher please?

And/or fix why the buildkit socket isn't accessible?

**Comment by nightfury1204** [comment]
@beastawakens thanks for reporting, I already updated the time and the version in this release: https://github.com/convox/convox/releases/tag/3.12.1
it should be resolved, let me know if you still see this

**Comment by beastawakens** [comment]
@nightfury1204 Amazing, thank you so much! Will try that out!  
Now just very much looking forward to buildkit 0.12 landing so we can support ECR image caching for vastly faster builds!
https://github.com/moby/buildkit/pull/3724

**Comment by beastawakens** [comment]
@nightfury1204 Just updated, and now I'm getting:

```
$ convox build /tmp/074381573 --app partner1-1295 --description '' --id --manifest convox.yml --development
Packaging source... OK
Uploading source... OK
Starting build... OK
could not connect to unix:///run/buildkit/buildkitd.sock after 30 trials
========== log ==========
```

So the issue is still persisting, just with more retries now 😞

**Comment by nightfury1204** [comment]
@beastawakens can you share your rack params?

**Comment by beastawakens** [comment]
@nightfury1204 Sure:

```╰─ convox rack params
high_availability   false
key_pair_name       dev-us-keypair-xxxxxxx
node_capacity_type  spot
node_type           t3a.large,r5.large,t3.large
proxy_protocol      true
region              us-west-2
release             3.12.1
```

**Comment by beastawakens** [comment]
We're also seeing builds hanging and just running for 4 hours before eventually being killed off.
Is it because HA is false?

**Comment by nightfury1204** [comment]
@beastawakens can you increase the node disk and check if it helps?

**Comment by beastawakens** [comment]
> @beastawakens can you increase the node disk and check if it helps?

I've increased this and am monitoring.  So far it seems to have helped...
