### ISSUE TITLE
How to access cluster with kubectl?

### ISSUE THREAD

**Issue by phronology** [convox/convox#659]
I'm trying to set up basic authentication on my AWS EKS cluster that I've created with Convox. To do this, I believe I need to use kubectl to access my cluster.

Using kubectl to gain direct access is [described here](https://docs.convox.com/management/direct-k8s-access/#configure-kubectl-to-point-at-your-rack) in the v1 documentation, however there doesn't appear to be any mention of it in the v2 documentation.

When I attempt to configure kubectl to point at my rack, as described in the v1 documentation:
`convox rack kubeconfig > $HOME/.kube/myrack-config
`
I get this error:
`ERROR: 0 args required`

I assume this is because the kubeconfig arg is deprecrated?

If so, was it replaced with a different way to access the cluster?

FYI I'm using Convox server version 3.12.4 

Any help on this would be appreciated, thanks.

**Comment by nightfury1204** [comment]
@phronology `convox rack kubeconfig > ~/.kube/config` should work. can you make sure you installed the latest cli: https://docs.convox.com/installation/cli/

**Comment by phronology** [comment]
Hey @nightfury1204, thanks for the quick response! 

I now realise the error - I was using the V2 docs for everything, I just tried using the setup and commands in [these docs](https://docs.convox.com/getting-started/introduction/) and kubectl worked, thanks.

If it's helpful to know, for me it wasn't clear which version of the docs [these ones](https://docs.convox.com/getting-started/introduction/) are - am I right in thinking these are V3? If so, it'd be useful to flag this at the top of the docs, or perhaps have a dropdown selector for the docs so it's clear which version is which.

Apologies if I've missed this, thanks for the help!

**Comment by ntner** [comment]
Hey @phronology 

We have two primary docs pages for
v2 - AWS ECS - https://docsv2.convox.com/
and 
v3 cloud agnostic k8s - EKS on AWS - https://docs.convox.com/

There are some legacy Gen 1 docs at the bottom of the v2 docs; however, you can't install a gen1 rack anymore so you shouldn't be using those docs much at all.

Our v2 docs should have no mention of kubectl as they are not running on Kubernetes.  If you were having issues getting the `convox rack kubeconfig > someLocation` command to work it is typically a local terminal problem.  You should always be able to > the command to a location and then reference the created config file in the kubectl command with the option `--kubeconfig=/path/to/config/file` in your `kubectl` command or by exporting the KUBECONFIG=/path/to/config/file and running `kubectl` commands natively.
