### ISSUE TITLE
BuildKit builds not able to see/use cache

### ISSUE THREAD

**Issue by beastawakens** [convox/convox#670]
Trying out the dedicated build node on v3.12.3, I see that builds do not use a local cache, and we get this error at the start of the build:

```
time="2023-07-12T16:37:55Z" level=warning msg="local cache import at /var/lib/buildkit not found due to err: could not read /var/lib/buildkit/index.json: open /var/lib/buildkit/index.json: no such file or directory" spanID=377bca3a664358f9 traceID=14d8f7a50f357d8b1e6d653e0dc4588c
```

Which suggests that the /var/lib/buildkit path is not being written correctly.  This lack of caching negates the main purpose of a dedicated build node.  I can see that in https://github.com/convox/convox/blob/allow-different-build-node-amitype/pkg/build/buildkit.go#L214C1-L215 we're trying to use the path but I wonder if that needs to be created in the Dockerfile.buildkit (https://github.com/convox/convox/blob/allow-different-build-node-amitype/Dockerfile.buildkit) or in the buildkit-daemonless.sh (https://github.com/convox/convox/blob/allow-different-build-node-amitype/scripts/buildctl-daemonless.sh)?

**Comment by beastawakens** [comment]
@nightfury1204 Or maybe a volume needs mounting to persist it between builds? 🤔

**Comment by nightfury1204** [comment]
closed by https://github.com/convox/convox/pull/694
