### ISSUE TITLE
Updates to the Rack (version, params etc) which cause node group migrations do not respect app/service level healthiness/scaling - causes downtime

### ISSUE THREAD

**Issue by beastawakens** [convox/convox#750]
**Rack version**: tested on 3.13.9 but I believe this would affect other versions since as well.
**Cloud**: AWS

**Scenario**

Triggering a rack update, or changing rack params that affect the node groups [node_disk, node_type etc]), cause the terraform to request the creation of new node groups alongside the existing ones.  Once the new node groups have been created, the old node groups will be torn down and discarded.

**Expected outcome**

Apps running on the Rack experience no downtime, as the horizontal pod autoscaler will start up new processes on the new node groups and wait for them to be healthy before allowing the old processes on the old node groups to be killed so the old node groups can be deleted.

**Actual outcome**

Apps can experience downtime as the old node groups are deleted before the new processes on the new node groups are healthy.  It may require confirmation but it looks like that as soon as the new node groups are created, the old node groups are marked for deletion straight away, regardless of process health.
We have a particular app with a startup time of 15-20 mins before it is healthy (pulling a *very* large image from ECR contributes to that), so we need a particularly slow rolling out.  Increasing the node_disk size on one of our Production racks yesterday caused a 15 minute outage.  

**Steps to reproduce**

Create an app with a health check but a long startup time (>10 minutes for instance).  Monitor the health endpoint for the app continuously.  Update a rack param that causes node group migration.   Experience the downtime!

**Comment by nightfury1204** [comment]
App serving traffic with 10 min startup time is huge. Setting pod disruptions budget will help in this case https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
