### ISSUE TITLE
Is Convox limiting access on free accounts?

### ISSUE THREAD

**Issue by ngothanhduoc** [convox/convox#755]
I am using the Convox service, and recently, I received a notification saying: "You have exceeded the monthly rate limit assigned to your Free organization for this request." When using the CLI, can you provide me with the updates regarding the restrictions on free account activities? I have searched, but I couldn't find any relevant documentation.

**Comment by ntner** [comment]
Hello @ngothanhduoc we do enforce monthly rate limits on actions to Free organizations.  These limits are set on values which would only effect organizations who far exceed regular use indented for Free users.  To date less than a handful have ever hit this quota.

If you feel you have reached this in error please contact quotas@convox.com with your organization-id and I will be happy to take a closer look.
